#!/usr/bin/env bash

# Maintained by Kazi Sanghati Sowharda Haque

# Set environment variables for local development
export APP_ENV=${APP_ENV:-local}
export APP_PORT=${APP_PORT:-80}
export DB_PORT=${DB_PORT:-3306}
export DB_ROOT_PASS=${DB_ROOT_PASS:-secret}
export DB_NAME=${DB_NAME:-homestead}
export DB_USER=${DB_USER:-homestead}
export DB_PASS=${DB_PASS:-secret}

COMPOSE="docker compose"
APP_NAME="storify-app"
NODE_SERVICE="storify-node"

if [ $# -gt 0 ];then
    if [ "$1" == "php" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            $APP_NAME \
            php "$@"
    elif [ "$1" == "artisan" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            $APP_NAME \
            php artisan "$@"
    elif [ "$1" == "composer" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            $APP_NAME \
            composer "$@"
    elif [ "$1" == "npm" ]; then
        shift 1
        $COMPOSE run --rm \
            -w /var/www/html \
            $NODE_SERVICE \
            npm "$@"
    else
        $COMPOSE "$@"
    fi
else
    $COMPOSE ps
fi
