version: '3.8'

networks:
  storify-net:
    driver: bridge
    name: storify-net

volumes:
  storify-mysql-data:
    driver: local
    name: storify-mysql-data
  
  storify-redis-data:
    driver: local
    name: storify-redis-data

services:
  storify-app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: dreamarray.com/l9app
    container_name: storify-app
    volumes:
     - .:/var/www/html
    ports:
      - "${APP_PORT}:80"
    networks:
      - storify-net
  
  storify-mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    image: dreamarray.com/l9mysql
    container_name: storify-mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    volumes:
     - storify-mysql-data:/var/lib/mysql
    networks:
      storify-net:
        aliases: 
          - db
  
  storify-redis:
    image: redis:alpine
    container_name: storify-redis
    volumes:
     - storify-redis-data:/data
    networks:
     - storify-net

  storify-node:
      build:
        context: ./docker/node
        dockerfile: Dockerfile
      image: dreamarray.com/node
      container_name: storify-node
      networks:
        - storify-net
      volumes:
        - .:/var/www/html